language: php
sudo: false

php:
    - 7.1
    - 7.2
    - 7.3
    - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
    - composer config disable-tls true
    - composer config secure-http false
    - composer install --prefer-source

script: vendor/bin/phpunit

notifications:
    email: false
